spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8849
        # 当前应用被sentinel监控的端口
        port: 8720
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"